ALTER TABLE `EXM_EXAM` MODIFY COLUMN `DESCRIPTION`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '' AFTER `PASS_SCORE`;
ALTER TABLE `EXM_EXAM` ADD COLUMN `MARK_START_TIME`  datetime NULL DEFAULT NULL COMMENT 'о���ʼ' AFTER `END_TIME`;
ALTER TABLE `EXM_EXAM` ADD COLUMN `MARK_END_TIME`  datetime NULL DEFAULT NULL COMMENT 'о' AFTER `MARK_START_TIME`;

ALTER TABLE `EXM_EXAM_TYPE` ADD COLUMN `USER_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'ûȨޡûöŷָ磺,2,45,66,57,' AFTER `NO`;
ALTER TABLE `EXM_EXAM_TYPE` ADD COLUMN `ORG_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Ȩ' AFTER `USER_IDS`;
ALTER TABLE `EXM_EXAM_TYPE` ADD COLUMN `POST_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'λȨ' AFTER `ORG_IDS`;

ALTER TABLE `EXM_PAPER` MODIFY COLUMN `DESCRIPTION`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '' AFTER `NAME`;

ALTER TABLE `EXM_PAPER_QUESTION` MODIFY COLUMN `DESCRIPTION`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '½' AFTER `NAME`;
ALTER TABLE `EXM_PAPER_QUESTION` ADD COLUMN `OPTIONS`  varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `NO`;

ALTER TABLE `EXM_PAPER_TYPE` ADD COLUMN `USER_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'ûȨޡûöŷָ磺,2,45,66,57,' AFTER `NO`;
ALTER TABLE `EXM_PAPER_TYPE` ADD COLUMN `ORG_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Ȩ' AFTER `USER_IDS`;
ALTER TABLE `EXM_PAPER_TYPE` ADD COLUMN `POST_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'λȨ' AFTER `ORG_IDS`;

ALTER TABLE `EXM_QUESTION_TYPE` ADD COLUMN `USER_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'ûȨޡûöŷָ磺,2,45,66,57,' AFTER `NO`;
ALTER TABLE `EXM_QUESTION_TYPE` ADD COLUMN `ORG_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Ȩ' AFTER `USER_IDS`;
ALTER TABLE `EXM_QUESTION_TYPE` ADD COLUMN `POST_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'λȨ' AFTER `ORG_IDS`;
