INSERT INTO `SYS_VER` VALUES (2, '1.1.2', '2019-03-03 13:20:00', 'ZHC', '');

ALTER TABLE `EXM_QUESTION` ADD COLUMN `VER` int DEFAULT NULL COMMENT '版本' AFTER `NO`;
ALTER TABLE `EXM_QUESTION` ADD COLUMN `SRC_ID` int DEFAULT NULL COMMENT '第一版本ID' AFTER `VER`;
UPDATE EXM_QUESTION SET VER = 1, SRC_ID = ID;