INSERT INTO `SYS_VER` VALUES (4, '1.1.4', '2019-09-05 09:58:00', 'ZHC', '');

DELETE FROM SYS_POST_RES
WHERE RES_ID IN (
	SELECT ID FROM SYS_RES
	WHERE PARENT_SUB LIKE '_1_99_%');
DELETE FROM SYS_RES WHERE PARENT_SUB LIKE '_1_99_%';

DELETE FROM SYS_POST_RES
WHERE RES_ID IN (
	SELECT ID FROM SYS_RES
	WHERE PARENT_SUB LIKE '_1_89_104_%');
DELETE FROM SYS_RES WHERE PARENT_SUB LIKE '_1_89_104_%';

DELETE FROM SYS_POST_RES
WHERE RES_ID IN (
	SELECT ID FROM SYS_RES
	WHERE PARENT_SUB LIKE '_1_89_105_%');
DELETE FROM SYS_RES WHERE PARENT_SUB LIKE '_1_89_105_%';