INSERT INTO `SYS_CRON` VALUES (2, '数据库备份', 'com.wcpdoc.quartz.job.DbBackJob', '0 0 0 1/1 * ? ', 1, 1, '2020-08-26 18:42:08');
INSERT INTO `SYS_CRON` VALUES (3, '自动阅卷', 'com.wcpdoc.exam.core.job.AutoMarkJob', '0/1 * * * * ? *', 1, 1, '2020-08-26 18:42:08');

INSERT INTO `SYS_VER` VALUES (11, '3.2.0', '2020-10-31 16:43:00', 'zhanghc', '');

INSERT INTO `SYS_DICT` VALUES (40, 'PAPER_MARK_TYPE', '1', '智能阅卷', 1);
INSERT INTO `SYS_DICT` VALUES (41, 'PAPER_MARK_TYPE', '2', '人工阅卷', 2);

ALTER TABLE `EXM_EXAM` ADD COLUMN `MARK_STATE` int(11) DEFAULT NULL COMMENT '1：已阅；2：未阅' AFTER `MARK_END_TIME`;

ALTER TABLE `EXM_MY_MARK` DROP COLUMN `AUTO_STATE`;

ALTER TABLE `EXM_PAPER` ADD COLUMN `MARK_TYPE` int(11) DEFAULT NULL COMMENT '1：智能阅卷；2：人工阅卷；数据字典：PAPER_MARK_TYPE' AFTER `TOTAL_SCORE`;

ALTER TABLE `EXM_PAPER_QUESTION_ANSWER` ADD COLUMN `PAPER_ID` int(11) DEFAULT NULL AFTER `NO`;

UPDATE `SYS_CRON` SET JOB_CLASS = 'com.wcpdoc.file.job.ClearFileJob' WHERE ID = 1