ALTER TABLE `exm_bulletin` ADD COLUMN `TOP_STATE`  int(11) NULL DEFAULT NULL COMMENT '1：是；2：否' AFTER `URL`;
ALTER TABLE `exm_bulletin` MODIFY COLUMN `STATE`  int(11) NULL DEFAULT NULL COMMENT '0：删除；1：正常；2：轮播展示' AFTER `NO`;
ALTER TABLE `exm_bulletin` DROP COLUMN `START_TIME`;
ALTER TABLE `exm_bulletin` DROP COLUMN `END_TIME`;
ALTER TABLE `exm_bulletin` DROP COLUMN `SHOW_TYPE`;

ALTER TABLE `exm_exam` MODIFY COLUMN `MARK_STATE`  int(11) NULL DEFAULT NULL COMMENT '阅卷状态（1：未阅卷；2：阅卷中；3：已阅卷；）' AFTER `MARK_END_TIME`;

ALTER TABLE `exm_exam_type` ADD COLUMN `RW_STATE`  int(11) NULL DEFAULT NULL COMMENT '1：开启；2：禁用' AFTER `STATE`;
ALTER TABLE `exm_exam_type` ADD COLUMN `READ_USER_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '读权限' AFTER `RW_STATE`;
ALTER TABLE `exm_exam_type` ADD COLUMN `WRITE_USER_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '写权限' AFTER `READ_USER_IDS`;
ALTER TABLE `exm_exam_type` MODIFY COLUMN `IMG_FILE_ID`  int(11) NULL DEFAULT NULL COMMENT '附件ID' AFTER `NAME`;

ALTER TABLE `exm_my_exam` MODIFY COLUMN `MARK_USER_ID`  int(11) NULL DEFAULT NULL COMMENT '阅卷人' AFTER `ANSWER_END_TIME`;

ALTER TABLE `exm_my_exam_detail` MODIFY COLUMN `MARK_USER_ID`  int(11) NULL DEFAULT NULL COMMENT '阅卷人ID' AFTER `ANSWER_TIME`;
ALTER TABLE `exm_my_exam_detail` MODIFY COLUMN `ANSWER_FILE_ID`  int(11) NULL DEFAULT NULL COMMENT '答案附件' AFTER `QUESTION_SCORE`;

ALTER TABLE `exm_paper_question` MODIFY COLUMN `SCORE_OPTIONS`  varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '1：半对半分（默认全对得分）；2：答案无顺序（默认答案有前后顺序）；3：大小写不敏感（默认大小写敏感）；4：包含答案得分（默认等于答案得分）' AFTER `SCORE`;

ALTER TABLE `exm_paper_type` ADD COLUMN `RW_STATE`  int(11) NULL DEFAULT NULL COMMENT '1：开启；2：禁用' AFTER `STATE`;
ALTER TABLE `exm_paper_type` ADD COLUMN `WRITE_USER_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '写权限' AFTER `RW_STATE`;
ALTER TABLE `exm_paper_type` MODIFY COLUMN `IMG_FILE_ID`  int(11) NULL DEFAULT NULL COMMENT '附件ID' AFTER `NAME`;

ALTER TABLE `exm_question` ADD COLUMN `VER`  int(11) NULL DEFAULT NULL COMMENT '版本' AFTER `SCORE_OPTIONS`;
ALTER TABLE `exm_question` ADD COLUMN `SRC_ID`  int(11) NULL DEFAULT NULL COMMENT '源ID' AFTER `VER`;
ALTER TABLE `exm_question` ADD COLUMN `NO`  int(11) NULL DEFAULT NULL COMMENT '排序' AFTER `SRC_ID`;
ALTER TABLE `exm_question` MODIFY COLUMN `STATE`  int(11) NULL DEFAULT NULL COMMENT '0：删除；1：启用；2：禁用' AFTER `ANALYSIS`;
ALTER TABLE `exm_question` MODIFY COLUMN `CREATE_USER_ID`  int(11) NULL DEFAULT NULL COMMENT '修改人' AFTER `STATE`;
ALTER TABLE `exm_question` MODIFY COLUMN `AI`  int(11) NULL DEFAULT NULL COMMENT '1：是；2：否；' AFTER `SCORE`;
ALTER TABLE `exm_question` MODIFY COLUMN `SCORE_OPTIONS`  varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '1：漏选得分；2：答案无顺序；3：大小写不敏感；' AFTER `AI`;

ALTER TABLE `exm_question_type` ADD COLUMN `RW_STATE`  int(11) NULL DEFAULT NULL COMMENT '1：开启；2：禁用' AFTER `STATE`;
ALTER TABLE `exm_question_type` ADD COLUMN `READ_USER_IDS`  varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '读权限' AFTER `RW_STATE`;
ALTER TABLE `exm_question_type` MODIFY COLUMN `IMG_FILE_ID`  int(11) NULL DEFAULT NULL COMMENT '附件ID' AFTER `NAME`;

ALTER TABLE `exm_question_type_open` MODIFY COLUMN `COMMENT_STATE`  int(11) NULL DEFAULT NULL COMMENT '评论状态(0：不显示；1：只读；2：可编辑,)' AFTER `QUESTION_TYPE_ID`;

ALTER TABLE `sys_parm` DROP COLUMN `FILE_UPLOAD_DIR`;
ALTER TABLE `sys_parm` DROP COLUMN `DB_BAK_DIR`;
ALTER TABLE `sys_parm` DROP COLUMN `PWD_TYPE`;
ALTER TABLE `sys_parm` DROP COLUMN `PWD_VALUE`;

ALTER TABLE `sys_user` MODIFY COLUMN `UPDATE_USER_ID`  int(11) NULL DEFAULT NULL COMMENT '修改人' AFTER `ROLES`;
ALTER TABLE `sys_user` MODIFY COLUMN `UPDATE_TIME`  datetime NULL DEFAULT NULL COMMENT '修改时间' AFTER `UPDATE_USER_ID`;
ALTER TABLE `sys_user` MODIFY COLUMN `STATE`  int(11) NULL DEFAULT NULL COMMENT '0：删除；1：正常；2：冻结；' AFTER `UPDATE_TIME`;
ALTER TABLE `sys_user` DROP COLUMN `TYPE`;