ALTER TABLE `EXM_MY_EXAM` ADD COLUMN `NO` int(11) DEFAULT NULL COMMENT '排序' AFTER `UPDATE_TIME`;

INSERT INTO `SYS_DICT` VALUES (50, 'QUESTION_SCORE_OPTIONS', '1', '漏选得分', 1);
INSERT INTO `SYS_DICT` VALUES (51, 'QUESTION_SCORE_OPTIONS', '2', '答案无顺序', 2);
INSERT INTO `SYS_DICT` VALUES (52, 'QUESTION_SCORE_OPTIONS', '3', '大小写不敏感', 3);

INSERT INTO `SYS_VER` VALUES (14, '3.4.0', '2021-12-31 12:00:00', 'zhanghc', '');