ALTER TABLE `EXM_MY_EXAM` ADD COLUMN `NO` int(11) DEFAULT NULL COMMENT '排序' AFTER `UPDATE_TIME`;

ALTER TABLE `exm_paper_question` MODIFY COLUMN `DESCRIPTION` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '章节描述' AFTER `NAME`;

INSERT INTO `SYS_DICT` VALUES (50, 'QUESTION_SCORE_OPTIONS', '1', '漏选得分', 1);
INSERT INTO `SYS_DICT` VALUES (51, 'QUESTION_SCORE_OPTIONS', '2', '答案无顺序', 2);
INSERT INTO `SYS_DICT` VALUES (52, 'QUESTION_SCORE_OPTIONS', '3', '大小写不敏感', 3);

INSERT INTO `SYS_CRON` VALUES (4, '自动考试', 'com.wcpdoc.exam.core.job.AutoExamJob', '0/1 * * * * ? *', 1, 1, '2020-08-26 18:42:08');

INSERT INTO `SYS_VER` VALUES (14, '3.4.0', '2021-12-31 12:00:00', 'zhanghc', '');