INSERT INTO `SYS_VER` VALUES (15, '3.5.0', '2022-01-28 15:36:51', 'zhanghc', '');

UPDATE EXM_PAPER_QUESTION_ANSWER PQA SET PQA.NO = -1 WHERE EXISTS ( SELECT 1 FROM EXM_QUESTION Z WHERE PQA.QUESTION_ID = Z.ID AND Z.TYPE = 2);

INSERT INTO EXM_PAPER_QUESTION_ANSWER(ANSWER, SCORE, `NO`, PAPER_ID, QUESTION_ID, PAPER_QUESTION_ID) SELECT GROUP_CONCAT(ANSWER), MAX(SCORE), 1, MAX(PAPER_ID), MAX(QUESTION_ID), MAX(PAPER_QUESTION_ID) FROM EXM_PAPER_QUESTION_ANSWER PQA WHERE PQA.NO = -1 AND EXISTS ( SELECT 1 FROM EXM_QUESTION Z WHERE PQA.QUESTION_ID = Z.ID AND Z.TYPE = 2) GROUP BY PQA.QUESTION_ID;

DELETE FROM EXM_PAPER_QUESTION_ANSWER WHERE NO = -1;

UPDATE EXM_QUESTION_ANSWER QA SET QA.NO = -1 WHERE EXISTS ( SELECT 1 FROM EXM_QUESTION Z WHERE QA.QUESTION_ID = Z.ID AND Z.TYPE = 2);

INSERT INTO EXM_QUESTION_ANSWER(ANSWER, SCORE, `NO`, QUESTION_ID) SELECT GROUP_CONCAT(ANSWER), MAX(SCORE), 1, MAX(QUESTION_ID) FROM EXM_QUESTION_ANSWER QA WHERE QA.NO = -1 AND EXISTS ( SELECT 1 FROM EXM_QUESTION Z WHERE QA.QUESTION_ID = Z.ID AND Z.TYPE = 2) GROUP BY QA.QUESTION_ID;

DELETE FROM EXM_QUESTION_ANSWER WHERE NO = -1;