ALTER TABLE `EXM_PAPER` ADD COLUMN `READ_USER_IDS` varchar(1024) DEFAULT NULL COMMENT '读权限' AFTER `PAPER_TYPE_ID`;
ALTER TABLE `EXM_QUESTION` ADD COLUMN `WRITE_USER_IDS` varchar(1024) DEFAULT NULL COMMENT '写权限' AFTER `AI_OPTIONS`;
ALTER TABLE `EXM_PAPER_TYPE` DROP COLUMN `READ_USER_IDS`;

UPDATE EXM_QUESTION QUESTION
	INNER JOIN EXM_QUESTION_TYPE QUESTION_TYPE ON QUESTION.QUESTION_TYPE_ID = QUESTION_TYPE.ID
	SET QUESTION.WRITE_USER_IDS = QUESTION_TYPE.WRITE_USER_IDS;
UPDATE EXM_PAPER PAPER
	INNER JOIN EXM_PAPER_TYPE PAPER_TYPE ON PAPER.PAPER_TYPE_ID = PAPER_TYPE.ID
	SET PAPER.READ_USER_IDS = PAPER_TYPE.READ_USER_IDS;
