ALTER TABLE SYS_USER ADD COLUMN TYPE int(11) DEFAULT NULL COMMENT '类型（0：管理员；1：考试用户；2：子管理员；3：阅卷用户）' AFTER PWD;

ALTER TABLE SYS_USER ADD COLUMN PARENT_ID int(11) DEFAULT NULL COMMENT '父级ID（TYPE == 3有效）' AFTER TYPE;

ALTER TABLE SYS_USER ADD COLUMN USER_IDS text DEFAULT NULL COMMENT '可管理用户IDS（子管理员有效）' AFTER PARENT_ID;

ALTER TABLE SYS_USER ADD COLUMN ORG_IDS text DEFAULT NULL COMMENT '可管理机构IDS（子管理员有效）' AFTER USER_IDS;

UPDATE SYS_USER SET ORG_ID = 0, TYPE = 0, PARENT_ID = 0 WHERE ID = 1;

UPDATE SYS_USER SET TYPE = 1, PARENT_ID = 1 WHERE ID != 1;

ALTER TABLE EXM_EXAM ADD COLUMN CREATE_USER_ID int(11) DEFAULT NULL COMMENT '创建用户ID' AFTER STATE;

UPDATE EXM_EXAM SET CREATE_USER_ID = 1;

ALTER TABLE EXM_EXER ADD COLUMN CREATE_USER_ID int(11) DEFAULT NULL COMMENT '创建用户ID' AFTER RMK_STATE;

UPDATE EXM_EXER SET CREATE_USER_ID = 1;

ALTER TABLE EXM_QUESTION ADD COLUMN CREATE_USER_ID int(11) DEFAULT NULL COMMENT '创建用户ID' AFTER QUESTION_TYPE_ID;

UPDATE EXM_QUESTION SET CREATE_USER_ID = 1;

ALTER TABLE EXM_QUESTION_TYPE ADD COLUMN CREATE_USER_ID int(11) DEFAULT NULL COMMENT '创建用户ID' AFTER NAME;

UPDATE EXM_QUESTION_TYPE SET CREATE_USER_ID = 1;

INSERT INTO SYS_VER VALUES (32, '4.3.0', '2023-10-09 10:51:00', 'zhanghc', '');