INSERT INTO `SYS_VER` VALUES (34, '4.4.0', '2024-02-09 09:14:00', 'zhanghc', '');

ALTER TABLE `EXM_EXAM` ADD COLUMN `LIMIT_MINUTE` int(11) DEFAULT NULL COMMENT '限制分钟（考试开始时间由用户第一次打开试卷时计时）' AFTER `END_TIME`;
ALTER TABLE `EXM_MY_EXAM` ADD COLUMN `EXAM_START_TIME` datetime(0) DEFAULT NULL COMMENT '考试开始时间' AFTER `MARK_USER_ID`;
ALTER TABLE `EXM_MY_EXAM` ADD COLUMN `EXAM_END_TIME` datetime(0) DEFAULT NULL COMMENT '考试结束时间' AFTER `EXAM_START_TIME`;

UPDATE EXM_EXAM  
SET START_TIME = STR_TO_DATE( DATE_FORMAT( START_TIME, '%Y-%m-%d %H:%i:00' ), '%Y-%m-%d %H:%i:%s' ),
END_TIME = STR_TO_DATE( DATE_FORMAT( END_TIME, '%Y-%m-%d %H:%i:00' ), '%Y-%m-%d %H:%i:%s' ),
LIMIT_MINUTE = 0;
