INSERT INTO `SYS_VER` VALUES (37, '4.5.0', '2024-05-31 12:16:00', 'zhanghc', '');

UPDATE `EXM_MY_EXAM` SET EXAM_START_TIME = ANSWER_START_TIME, EXAM_END_TIME = ANSWER_END_TIME WHERE EXAM_START_TIME IS NULL;

ALTER TABLE `EXM_EXAM` ADD COLUMN `USER_NUM` int(11) DEFAULT NULL COMMENT '考试用户数量' AFTER `SXES`;
ALTER TABLE `EXM_MY_EXAM` DROP COLUMN `ANSWER_START_TIME`;
ALTER TABLE `EXM_MY_EXAM` DROP COLUMN `ANSWER_END_TIME`;

UPDATE `EXM_EXAM` EXAM SET EXAM.USER_NUM = (SELECT COUNT(*) FROM EXM_MY_EXAM MY_EXAM WHERE EXAM.ID = MY_EXAM.EXAM_ID);
ALTER TABLE `EXM_MY_EXAM` ADD INDEX `MY_EXAM_EU` ( `EXAM_ID`,`USER_ID` );