INSERT INTO `SYS_VER` VALUES (38, '4.6.0', '2024-10-16 13:10:00', 'zhanghc', '');

ALTER TABLE `EXM_EXAM` ADD COLUMN `LOGIN_TYPE` int(11) DEFAULT NULL COMMENT '登录方式（1：正常登录；2：免登录；）' AFTER `SHOW_TYPE`;
UPDATE EXM_EXAM SET LOGIN_TYPE = 1;

ALTER TABLE `EXM_MY_EXAM` CHANGE COLUMN `EXAM_START_TIME` `ANSWER_START_TIME` datetime(0) DEFAULT NULL COMMENT '答题开始时间';  
ALTER TABLE `EXM_MY_EXAM` CHANGE COLUMN `EXAM_END_TIME` `ANSWER_END_TIME` datetime(0) DEFAULT NULL COMMENT '答题结束时间';
ALTER TABLE `SYS_PARM` ADD COLUMN `M_HOST` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '移动端地址' AFTER `CUSTOM_CONTENT`;
ALTER TABLE `SYS_USER` MODIFY COLUMN `TYPE` int(11) DEFAULT NULL COMMENT '类型（0：管理员；1：考试用户；2：子管理员；3：阅卷用户；4：免登录用户）' AFTER `PWD`;
INSERT INTO `SYS_DICT`(`ID`, `DICT_INDEX`, `DICT_KEY`, `DICT_VALUE`, `NO`) VALUES (56, 'LOGIN_TYPE', '1', '正常登录', 1);
INSERT INTO `SYS_DICT`(`ID`, `DICT_INDEX`, `DICT_KEY`, `DICT_VALUE`, `NO`) VALUES (57, 'LOGIN_TYPE', '2', '免登录', 2);