ALTER TABLE `EXM_EXAM_RULE` CHANGE COLUMN `QUESTION_TYPE_ID` `QUESTION_BANK_ID` INT(11) DEFAULT NULL COMMENT '题库ID' AFTER `TYPE`;
ALTER TABLE `EXM_EXER` CHANGE COLUMN `QUESTION_TYPE_ID` `QUESTION_BANK_ID` INT(11) DEFAULT NULL COMMENT '题库ID' AFTER `NAME`;
ALTER TABLE `EXM_QUESTION` CHANGE COLUMN `QUESTION_TYPE_ID` `QUESTION_BANK_ID` INT(11) DEFAULT NULL COMMENT '题库ID' AFTER `STATE`;
ALTER TABLE `EXM_QUESTION_TYPE` RENAME TO `EXM_QUESTION_BANK`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `OBJECTIVE_NUM` INT(11) DEFAULT NULL COMMENT '客观题数量' AFTER `NAME`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `SUBJECTIVE_NUM` INT(11) DEFAULT NULL COMMENT '主观题数量' AFTER `OBJECTIVE_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `SINGLE_NUM` INT(11) DEFAULT NULL COMMENT '单选题数量' AFTER `SUBJECTIVE_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `MULTIPLE_NUM` INT(11) DEFAULT NULL COMMENT '多选题数量' AFTER `SINGLE_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `FILL_BLANK_OBJ_NUM` INT(11) DEFAULT NULL COMMENT '填空题客观数量' AFTER `MULTIPLE_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `FILL_BLANK_SUB_NUM` INT(11) DEFAULT NULL COMMENT '填空题主观数量' AFTER `FILL_BLANK_OBJ_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `JUDGE_NUM` INT(11) DEFAULT NULL COMMENT '判断题数量' AFTER `FILL_BLANK_SUB_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `QA_OBJ_NUM` INT(11) DEFAULT NULL COMMENT '问答题客观数量' AFTER `JUDGE_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `QA_SUB_NUM` INT(11) DEFAULT NULL COMMENT '问答题主观数量' AFTER `QA_OBJ_NUM`;
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `QUESTION_NUM` INT(11) DEFAULT NULL COMMENT '试题总数量' AFTER `QA_SUB_NUM`;

INSERT INTO `SYS_DICT`(`ID`, `DICT_INDEX`, `DICT_KEY`, `DICT_VALUE`, `NO`) VALUES (58, 'STATE_PS', '1', '发布', 1);
INSERT INTO `SYS_DICT`(`ID`, `DICT_INDEX`, `DICT_KEY`, `DICT_VALUE`, `NO`) VALUES (59, 'STATE_PS', '2', '暂停', 2);

UPDATE EXM_QUESTION_BANK QUESTION_BANK 
SET QUESTION_BANK.OBJECTIVE_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.MARK_TYPE = 1 ),
	QUESTION_BANK.OBJECTIVE_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.MARK_TYPE = 1 ),
	QUESTION_BANK.SUBJECTIVE_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.MARK_TYPE = 2 ),
	QUESTION_BANK.SINGLE_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.TYPE = 1 ),
	QUESTION_BANK.MULTIPLE_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.TYPE = 2 ),
	QUESTION_BANK.FILL_BLANK_OBJ_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.TYPE = 3  AND T.MARK_TYPE = 1),
	QUESTION_BANK.FILL_BLANK_SUB_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.TYPE = 3 AND T.MARK_TYPE = 2),
	QUESTION_BANK.JUDGE_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.TYPE = 4 ),
	QUESTION_BANK.QA_OBJ_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.TYPE = 5 AND T.MARK_TYPE = 1),
	QUESTION_BANK.QA_SUB_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 AND T.TYPE = 5 AND T.MARK_TYPE = 2),
	QUESTION_BANK.QUESTION_NUM = ( SELECT COUNT( * ) FROM EXM_QUESTION T WHERE QUESTION_BANK.ID = T.QUESTION_BANK_ID AND T.STATE = 1 );

INSERT INTO `SYS_VER`(`ID`, `VER`, `UPDATE_TIME`, `AUTHOR`, `REMARK`) VALUES (40, '5.0.0', '2025-02-20 14:56:00', 'zhanghc', '');