INSERT INTO SYS_VER VALUES (42, '5.1.1', '2025-04-02 10:17:00', 'zhanghc', '');

UPDATE EXM_QUESTION_BANK QB
SET 
    OBJECTIVE_NUM =      (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.MARK_TYPE = 1),
    SUBJECTIVE_NUM =     (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.MARK_TYPE = 2),
    SINGLE_NUM =         (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.TYPE = 1),
    MULTIPLE_NUM =       (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.TYPE = 2),
    FILL_BLANK_OBJ_NUM = (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.TYPE = 3 AND Q.MARK_TYPE = 1),
    FILL_BLANK_SUB_NUM = (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.TYPE = 3 AND Q.MARK_TYPE = 2),
    JUDGE_NUM =          (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.TYPE = 4),
    QA_OBJ_NUM =         (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.TYPE = 5 AND Q.MARK_TYPE = 1),
    QA_SUB_NUM =         (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1 AND Q.TYPE = 5 AND Q.MARK_TYPE = 2),
    QUESTION_NUM =       (SELECT COUNT(*) FROM EXM_QUESTION Q WHERE Q.QUESTION_BANK_ID = QB.ID AND Q.STATE = 1);