INSERT INTO SYS_VER VALUES (43, '5.2.0', '2025-05-01 14:35:00', 'zhanghc', '');

ALTER TABLE `SYS_PARM` ADD COLUMN `VERHUB_URL` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '版本中心链接' AFTER `M_HOST`;
ALTER TABLE `SYS_PARM` ADD COLUMN `APP_ID` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '应用ID' AFTER `VERHUB_URL`;
ALTER TABLE `SYS_PARM` ADD COLUMN `APP_VER` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '应用ID' AFTER `APP_ID`;
ALTER TABLE `SYS_PARM` ADD COLUMN `APP_REL_VER` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '应用发布版本' AFTER `APP_VER`;
ALTER TABLE `SYS_PARM` ADD COLUMN `APP_REL_TIME` datetime(0) DEFAULT NULL COMMENT '应用发布时间' AFTER `APP_REL_VER`;
UPDATE `SYS_PARM` SET `APP_REL_VER`='5.2.0',`APP_REL_TIME`='2025-05-01 14:35:00',`APP_ID`=REPLACE(UUID(), '-', '') WHERE `ID`=1;
UPDATE `SYS_PARM` SET `VERHUB_URL`='http://verhub.xiaomaokaiyuan.com/api/ver/latest',`APP_VER`='5.2.0' WHERE `ID`=1;

INSERT INTO `SYS_CRON`(`ID`, `NAME`, `JOB_CLASS`, `CRON`, `STATE`, `UPDATE_USER_ID`, `UPDATE_TIME`) VALUES (3, '版本检测', 'com.wcpdoc.base.job.VerCheckJob', '0 0 0 1/1 * ? ', 1, 1, '2025-04-08 20:16:10');

ALTER TABLE `EXM_EXAM` ADD COLUMN `USER_IDS` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '用户IDS' AFTER `SXES`;
ALTER TABLE `EXM_EXAM` ADD COLUMN `ORG_IDS` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '机构IDS' AFTER `USER_IDS`;
ALTER TABLE `EXM_EXAM` ADD COLUMN `MARK_USER_IDS` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '阅卷用户IDS' AFTER `ORG_IDS`;
ALTER TABLE `EXM_EXAM` DROP COLUMN `USER_NUM`;

SET SESSION GROUP_CONCAT_MAX_LEN = 10485760;
UPDATE EXM_EXAM EXAM
SET EXAM.USER_IDS = (
    SELECT CONCAT(',', GROUP_CONCAT(MY_EXAM.USER_ID), ',')
    FROM EXM_MY_EXAM MY_EXAM
    WHERE MY_EXAM.EXAM_ID = EXAM.ID);

ALTER TABLE `EXM_QUESTION` ADD COLUMN `IMG_FILE_IDS` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '图片IDS' AFTER `TITLE`;

UPDATE EXM_EXAM E1
	JOIN (
	    SELECT 
	        ID,
	        NAME,
	        (
	            SELECT COUNT(*) 
	            FROM EXM_EXAM E2 
	            WHERE E2.NAME = E1.NAME AND E2.ID <= E1.ID
	        ) AS ROW_NUM
	    FROM EXM_EXAM E1
	) AS NUMBERED ON E1.ID = NUMBERED.ID
	SET E1.NAME = CONCAT(E1.NAME, '_', NUMBERED.ROW_NUM)
	WHERE NUMBERED.ROW_NUM > 1;
