-- 记录版本
INSERT INTO `SYS_VER` VALUES (49, '5.7.0', '2025-10-28 09:24:00', 'zhanghc', '');
UPDATE SYS_PARM SET APP_VER = '5.7.0';

-- 修改我的考试的表名，和我的练习的表名对齐
RENAME TABLE `EXM_MY_QUESTION` TO `EXM_MY_EXAM_QUESTION`;
RENAME TABLE `EXM_MY_QUESTION_HIS` TO `EXM_MY_EXAM_QUESTION_HIS`;

-- 管理员创建练习选择根机构时，统计列表页展示了临时登录用户的信息（默认临时登录用户机构为1，现在改为0，也就是不属于任何机构）
UPDATE SYS_USER SET ORG_ID = 0 WHERE TYPE = 4;

-- 文字统一
UPDATE SYS_DICT SET DICT_VALUE = '临时登录' WHERE DICT_VALUE = '免登录';
UPDATE SYS_DICT SET DICT_VALUE = '账号登录' WHERE DICT_VALUE = '正常登录';
ALTER TABLE `EXM_EXAM` MODIFY COLUMN `LOGIN_TYPE` int(11) DEFAULT NULL COMMENT '登录方式（1：账号登录；2：临时登录；）数据字典：LOGIN_TYPE' AFTER `SHOW_TYPE`;

-- bug：题库改为逻辑删除（直接删除会导致练习引用为空）
ALTER TABLE `EXM_QUESTION_BANK` ADD COLUMN `STATE` int(11) DEFAULT NULL COMMENT '状态（0：删除；1：正常；）' AFTER `QUESTION_NUM`;
UPDATE EXM_QUESTION_BANK SET STATE = 1;
